name: Project Release

on:
  release:
    types: [created, edited]

  workflow_dispatch:
    inputs:
      release_tag:
        description: "Project release version number or tag (e.g. v1.0.0)"
        required: true
        default: "v0.0.0"

jobs:
  main:
    name: 'Run'
    uses: usf-cs272-fall2022/action-workflows/.github/workflows/project-release.yml@main
    with:
      release_tag: ${{ github.event.inputs.release_tag }}